services:
  django:
    container_name: Backend
    build:
      context: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
  # react:
  #   container_name: Frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app

  db:
    container_name: Database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: minha_senha
    volumes:
      - ./db-data:/backup