# Generated by Django 4.2.11 on 2024-04-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
    ]
